theme: './theme'

siteConfig:
  url: https://blog.never.pet
  title: Never迷の小窝
  author: NeverBehave
  email: i@never.pet
  description: 迷の生物的迷の小窝

themeConfig:
  disqus: neverbehave
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
    - text: Friends
      link: /friends.html
  social:
    twitter: _NeverBehave_
    github: NeverBehave
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
