theme: "./theme"

permalinks:
  post: /:year/:month/:day/:slug
  page: /:slug

siteConfig:
  url: https://blog.never.pet
  title: Never迷の小窝
  author: NeverBehave
  email: i@never.pet
  description: 迷の生物的迷の小窝

themeConfig:
  footer: 
    since: 2017
    to: 2020
  disqus: neverbehave
  nav:
    - text: Home
      link: /
    - text: About
      link: /about
    - text: Social
      link: https://never.pet
    - text: Friends
      link: /friends

plugins:
  - resolve: saber-plugin-query-posts
    options:
      perPage: 12
      permalinks:
        category: "/blog/category/:name"
        tag: "/blog/tag/:name"
      categoriesMap:
        "数码": "digital"
        "技术": "technology"
        "随笔": "uncategorized"
        "事项": "announcement"
  - resolve: saber-plugin-feed
    options:
      atomFeed: "/feed/atom.xml"
      jsonFeed: "/feed/index.json"
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-image
    options:
      sizes: 
        - 1200
        - 720
        - 480
      placeholder: true
      blendIn: false
  - resolve: saber-plugin-sitemap
    options:
      template: "./sitemap.xml"
  - resolve: saber-plugin-ga-lite
    options:
      trackId: 'UA-85513844-3'
